# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

network:
  instance_tag: frontend-source
  name: flatten-staging-frontend
  subnetwork_name: frontend-subnet
# [START handlers]
handlers:
  - url: /assets/js/(.*)
    static_files: dist/assets/js/\1
    upload: dist/assets/js/(.*)
  - url: /assets/css/(.*)
    static_files: dist/assets/css/\1
    upload: dist/assets/css/(.*)
  - url: /static/media/(.*)
    static_files: dist/static/media/\1
    upload: dist/static/media/(.*)
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
# [END handlers]
