# [START runtime]
runtime: nodejs10
# [END runtime]

# [START handlers]
handlers:
  - url: /assets/js/(.*)
    static_files: dist/assets/js/\1
    upload: dist/assets/js/(.*)
  - url: /assets/css/(.*)
    static_files: dist/assets/css/\1
    upload: dist/assets/css/(.*)
  - url: /static/media/(.*)
    static_files: dist/static/media/\1
    upload: dist/static/media/(.*)
  - url: /logo_nav.png
    static_files: dist/logo_nav.png
    upload: dist/logo_nav.png
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
# [END handlers]
